# Generated by Django 4.2.2 on 2023-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todomodel_dedline_todomodel_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="complete",
            field=models.CharField(
                choices=[("0", "Incomplete"), ("1", "Complete")],
                default="0",
                max_length=1,
            ),
        ),
    ]
