# Generated by Django 4.2.2 on 2023-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todomodel_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="dedline",
            field=models.DateField(blank=True),
        ),
    ]
