# Generated by Django 4.2.2 on 2023-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todomodel_dedline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="dedline",
            field=models.DateField(null=True),
        ),
    ]
